django_project/accounts/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

django_project/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView


urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post2_detail"),
    path("post/<int:pk>/edit/>", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("blog.urls")),
    path("", include("posts.urls")),
    path("", include("pages.urls")),

]

django_project/pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView


urlpatterns = [
    path("", HomePageView.as_view(), name='home'),
    path("about/", AboutPageView.as_view(), name='about'),
]

django_project/posts/urls.py
from django.urls import path
from .views import HomePageView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    ]

django_project/accounts/models.py
from django.db import models

# Create your models here.

django_project/blog/models.py
from django.db import models
from django.urls import reverse


class Post2(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE,)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post2_detail", kwargs={"pk": self.pk})

django_project/posts/models.py
from django.db import models


class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50]

django_project/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

django_project/blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post2


class BlogListView(ListView):
    model = Post2
    template_name = "home.html"


class BlogDetailView(DetailView):
    model = Post2
    template_name = "post_detail.html"


class BlogCreateView(CreateView):
    model = Post2
    template_name = "post_new.html"
    fields = ["title", "author", "body"]


class BlogUpdateView(UpdateView):
    model = Post2
    template_name = "post_edit.html"
    fields = ["title", "body"]


class BlogDeleteView(DeleteView):
    model = Post2
    template_name = "post_delete.html"
    success_url = reverse_lazy("home")

django_project/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"


class AboutPageView(TemplateView):
    template_name = "about.html"

django_project/posts/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Post


class HomePageView(ListView):
    model = Post
    template_name = "home.html"

django_project/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>About site</h1>
{% endblock content %}

django_project/templates/base.html
{% load static %}
<html>
    <head>
        <title>Django blog</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <header>
            <div class="nav-left">
                <h1><a href="{% url 'home' %}">Django blog</a></h1>
            </div>
            <div class="nav-right">
                <a href="{% url 'post_new' %}">+ New Blog Post</a>
            </div>
        </header>
        {% if user.is_authenticated %}
            <p>Hi {{ user.username }}!</p>
            <a href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <p>You are not logged in</p>
            <a href="{% url 'login' %}">Log In</a> |
            <a href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

django_project/templates/home.html
{% extends "base.html" %}

{% block content %}
{% for post in post2_list %}
    <div class="post-entry">
        <h2><a href="{% url 'post2_detail' post.pk %}">{{ post.title }}</a></h2>
        <p>{{ post.body }}</p>
    </div>
{% endfor %}
{% endblock content %}

django_project/templates/post_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete post</h1>
<form  action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ post2.title }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

django_project/templates/post_detail.html
{% extends "base.html" %}

{% block content %}
<div class="post-entry">
    <h2>{{  post2.title }}</h2>
    <p>{{  post2.body }}</p>
</div>

<a href="{% url 'post_edit' post2.pk %}">+ Edit Post Blog</a> <br>
<a href="{% url 'post_delete' post2.pk %}">+ Delete Post Blog</a>
{% endblock content %}

django_project/templates/post_edit.html
{% extends "base.html" %}

{% block content %}
<h1>Edit post</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock content %}

django_project/templates/post_new.html
{% extends "base.html" %}

{% block content %}
<h1>New post</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}